name: "Build QA"
on:
  pull_request:
    branches:
      - qa
  push:
    branches:
      - qa
jobs:
  flutter_test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter test

  build_android:
    name: Build QA
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter build apk --debug --flavor qa -t lib/main_qa.dart --split-per-abi
      - name: push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

  build_ios:
    name: Build QA
    needs: [ flutter_test ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - run: flutter pub get
      - run: flutter build ipa --debug --flavor qa -t lib/main_qa.dart --no-codesign
      - name: push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/archive/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}